---
version: "3.9"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: 'monitoring-grafana'
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning/datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    env_file:
      - ./grafana/config.monitoring
    environment:
      - TZ=Europe/Minsk
    restart: unless-stopped
#    networks:
#      - monitoring
#networks:
#  monitoring:
#    driver: host

volumes:
    grafana_data:
