---
version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: 'monitoring-prometheus'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    environment:
      TZ: "Europe/Minsk"
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:9.3.2
    container_name: 'monitoring-grafana'
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring
    environment:
      - TZ=Europe/Minsk
    restart: unless-stopped
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: 'monitoring-node-exporter'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    environment:
      - TZ=Europe/Minsk
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
    prometheus_data:


#  alertmanager:
#    image: prom/alertmanager:v0.25.0
#    ports:
#      - 9093:9093
#    volumes:
#      - ./alertmanager/:/alertmanager
#      - ./alertmanager/:/etc/alertmanager/
#      - ./alertmanager/templates:/etc/alertmanager/templates
#    command:
#      - '--config.file=/etc/alertmanager/config.yml'
#      - '--storage.path=/alertmanager'
#    environment:
#      - TZ=Europe/Minsk
#    restart: unless-stopped

#  loki:
#    image: grafana/loki:main-380caba
#    ports:
#      - 3100:3100
#    volumes:
#      - ./loki/:/etc/loki/
#    command:
#      - '--config.file=/etc/loki/loki-config.yml'
#    environment:
#      - TZ=Europe/Minsk
#    restart: unless-stopped
#
#  promtail:
#    image: grafana/promtail:main-380caba
#    volumes:
#      - /var/log:/var/log:ro
#      - ./promtail/:/etc/promtail/
#    command:
#      - '--config.file=/etc/promtail/promtail-config.yml'
#    environment:
#      - TZ=Europe/Minsk
#    restart: unless-stopped

#volumes:
#    prometheus_data:
#    grafana_data:
