---
plugin: aws_ec2
aws_profile: default
regions:
  - us-east-1
filters:
  tag:Name:
    - ubuntu
    - amazon
  instance-state-name : running
keyed_groups:
  - prefix: ubuntu
    key: tags['ubuntu']
  - prefix: amazon
    key: tags['amazon']
