---
- name: Install and run apache
  hosts: all
  become: yes

  tasks:
  - block: #ubuntu
      - name: Install apache on ubuntu
        apt: name=apache2 state=latest
      - name: Run apache on ubuntu
        ansible.builtin.systemd: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

#    handlers:
#      - name: Restart6Apache ubuntu
#        service: name=apache2 state=restarted
#      - name: Restart Apache amazon
#        service: name=httpd state=restarted